# Generated by Django 5.1 on 2024-08-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='resumeUrl',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
