# Generated by Django 5.1 on 2024-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_userprofile_resume_userprofile_resumeurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/media'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='resumeUrl',
            field=models.FileField(blank=True, null=True, upload_to='media/resumes'),
        ),
    ]
