# Generated by Django 5.0.7 on 2024-07-29 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_chat_messagegroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagegroup',
            old_name='Chat',
            new_name='chat',
        ),
    ]
