# Generated by Django 5.0.7 on 2024-08-18 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_user'),
        ('api', '0007_rename_reciever_application_receiver_and_more'),
    ]

    operations = [
    ]
