# Generated by Django 5.0.7 on 2024-08-21 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_merge_20240818_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('film', 'Film & Media')], default='tech', max_length=50),
        ),
    ]
