# Generated by Django 5.1 on 2024-09-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_post_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'permissions': [('can_moderate_post', 'Can moderate post status')]},
        ),
    ]
