# Generated by Django 5.1 on 2024-08-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_userprofile_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('tech', 'Technology'), ('film', 'Film & Media')], default='tech', max_length=2500),
        ),
    ]
