# Generated by Django 5.1 on 2024-08-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_post_desc_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='message',
            field=models.CharField(default='1', max_length=280),
            preserve_default=False,
        ),
    ]
