services:
  backend:
    image: dbradley2003/backend:latest
    container_name: backend-container
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_PWD=${DB_PWD}
      - DB_USER=${DB_USER}
    ports:
      - "8000:8000"

  frontend:
    image: dbradley2003/frontend:latest
    container_name: frontend-container
    environment: 
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3000:3000"


    