version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: teamup-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app  # Optional for live code updates in development
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: teamup-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL= http://backend:8000  # Frontend's backend URL
      - APP_REDIRECT_URI=http://localhost:3000

 