version: '3.8'

networks:
  backend:
    driver: bridge

services:
  backend:
    image: dbradley2003/backend:latest
    container_name: backend-container
    networks:
      - backend
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY
      - DB_NAME
      - DB_HOST
      - DB_PORT
      - DB_PWD
      - DB_USER

  frontend:
    image: dbradley2003/frontend:latest
    container_name: frontend-container
    networks:
      - backend
    ports:
      - "3000:3000"


    