name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Pull Docker Images
      - name: Pull Docker Images
        run: |
          sudo docker pull dbradley2003/backend:latest
          sudo docker pull dbradley2003/frontend:latest

      # Step 3: Stop and Remove Existing Containers
      - name: Stop and Remove Existing Containers
        run: |
          sudo docker compose down || true

      # Step 4: Deploy Containers with Docker Compose
      - name: Deploy Containers
        run: |
            export SECRET_KEY="${{ secrets.SECRET_KEY }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_HOST="${{ secrets.DB_HOST }}"
            export DB_PORT="${{ secrets.DB_PORT }}"
            export DB_PWD="${{ secrets.DB_PWD }}"
            export DB_USER="${{ secrets.DB_USER }}"
            sudo docker compose up -d
