name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Backend Docker Image
      run: sudo docker pull dbradley2003/backend:latest
    
    - name: Pull Frontend Docker Image
      run: sudo docker pull dbradley2003/frontend:latest

    - name: Delete Old Backend Container
      run: sudo docker rm -f backend-container || true

    - name: Delete Old Frontend Container
      run: sudo docker rm -f frontend-container || true

  
    - name: Run Backend Container
      run: sudo docker run -d -p 8000:8000 --name backend-container dbradley2003/backend:latest

    
    - name: Run Frontend Container
      run: sudo docker run -d -p 3000:80 --name frontend-container dbradley2003/frontend:latest