name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Pull Docker Images
      - name: Pull Docker Images
        run: |
          sudo docker pull dbradley2003/backend:latest
          sudo docker pull dbradley2003/frontend:latest

      # Step 3: Stop and Remove Existing Containers
      - name: Stop and Remove Existing Containers
        run: |
          sudo docker compose down || true
    
      - name: Create .env File
        run: |
            echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" >> temp.env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> temp.env
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> temp.env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> temp.env
            echo "DB_PWD=${{ secrets.DB_PWD }}" >> temp.env
            echo "DB_USER=${{ secrets.DB_USER }}" >> temp.env
            

      # Step 4: Deploy Containers with Docker Compose
      - name: Deploy Containers
        run: |
            sudo docker compose --env-file temp.env up -d
