name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout Code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Pull Docker Images
      - name: Pull Docker Images
        run: |
          sudo docker pull dbradley2003/backend:latest
          sudo docker pull dbradley2003/frontend:latest

      # Step 3: Stop and Remove Existing Containers
      - name: Stop and Remove Existing Containers
        run: |
          sudo docker compose down || true

      # Step 4: Deploy Containers with Docker Compose
      - name: Deploy Containers
        run: |
            sudo docker compose up -d \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_PWD="${{ secrets.DB_PWD }}" \
            -e DB_USER="${{ secrets.DB_USER }}"
