name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Pull Backend Docker Image



      - name: Pull Backend Docker Image
        run: sudo docker pull dbradley2003/backend:latest

      # Step 2: Pull Frontend Docker Image
      - name: Pull Frontend Docker Image
        run: sudo docker pull dbradley2003/frontend:latest

      # Step 3: Remove Old Backend Container
      - name: Delete Old Backend Container
        run: sudo docker rm -f backend-container || true

      # Step 4: Remove Old Frontend Container
      - name: Delete Old Frontend Container
        run: sudo docker rm -f frontend-container || true
         

      # Step 5: Run Backend Container
      
      - name: Run Backend Container
        run: |
          sudo docker run -d \
            -p 8000:8000 \
            -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
            -e DB_NAME="${{ secrets.DB_NAME }}" \
            -e DB_HOST="${{ secrets.DB_HOST }}" \
            -e DB_PORT="${{ secrets.DB_PORT }}" \
            -e DB_PWD="${{ secrets.DB_PWD }}" \
            -e DB_USER="${{ secrets.DB_USER }}" \
            --name backend-container \
            dbradley2003/backend:latest

      # Step 6: Run Frontend Container
      - name: Run Frontend Container
        run: |
          sudo docker run -d \
            -p 3000:80 \
            --name frontend-container \
            dbradley2003/frontend:latest


